version: "3.1"

networks:
  network3:
    name: network3

services:
  nginx:
    container_name: nginx
    image: "nginx:stable-alpine"
    ports: 
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www
    networks:
      - network3
    depends_on:
      - php
      - mysql8.0

  php:
    container_name: php
    build: 
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www
      -  ./php/php.ini:/usr/local/etc/php/php.ini
      # - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - network3
    depends_on:
      - mysql8.0
    
  mysql8.0:
    container_name: mysql8.0
    image: mysql:8.0
    ports:
      - "3316:3306"
    env_file:
      - env/mysql.env
    volumes:
      - db_data:/var/lib/mysql
      - ./:/var/www
    networks:
      - network3

  phpmyadmin2:
    container_name: phpmyadmin2
    image: phpmyadmin
    ports:
     - 1500:80
    environment:
      - PMA_HOST=mysql8.0
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=50M
    networks:
      - network3
    depends_on:
      - mysql8.0
    
  # composer:
  #   build:
  #     context: dockerfiles
  #     dockerfile: composer.Dockerfile
  #   volumes:
  #     - ./src:/var/www/laravel
  #   profiles:
  #     - composer

  # artisan:
  #   build:
  #     context: dockerfiles
  #     dockerfile: php.Dockerfile
  #   volumes:
  #     - ./src:/var/www/laravel
  #   entrypoint: ["php", "/var/www/laravel/artisan"]
  #   networks:
  #     - network3
  #   profiles:
  #     - artisan

volumes:
  db_data: